<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>git-rebase-todo</string>
		<string>git-rebase</string>
	</array>
	<key>name</key>
	<string>Git Rebase</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>^#.*$</string>
			<key>name</key>
			<string>comment.line.number-sign</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(x|exec)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.language.rebase.exec.git-rebase</string>
				</dict>
			</dict>
			<key>end</key>
			<string>
|$</string>
			<key>name</key>
			<string>meta.exec.rebase.git-rebase</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.shell</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.commit-hash.rebase.git-rebase</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.commit-message.rebase.git-rebase</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^p(?:ick)? ([0-9a-f]+) ?(.*)</string>
			<key>name</key>
			<string>constant.language.rebase.pick.git-rebase</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.commit-hash.rebase.git-rebase</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.commit-message.rebase.git-rebase</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^e(?:dit)? ([0-9a-f]+) ?(.*)</string>
			<key>name</key>
			<string>constant.language.rebase.edit.git-rebase</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.commit-hash.rebase.git-rebase</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.commit-message.rebase.git-rebase</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^f(?:ixup)? ([0-9a-f]+) ?(.*)</string>
			<key>name</key>
			<string>constant.language.rebase.fixup.git-rebase</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.commit-hash.rebase.git-rebase</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.commit-message.rebase.git-rebase</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^r(?:eword)? ([0-9a-f]+) ?(.*)</string>
			<key>name</key>
			<string>constant.language.rebase.reword.git-rebase</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.commit-hash.rebase.git-rebase</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.commit-message.rebase.git-rebase</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^s(?:quash)? ([0-9a-f]+) ?(.*)</string>
			<key>name</key>
			<string>constant.language.rebase.squash.git-rebase</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.git-rebase</string>
	<key>uuid</key>
	<string>89f61c99-f7ae-4cd1-b5f1-92a1afb50242</string>
</dict>
</plist>
