<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>gitignore</string>
	</array>
	<key>name</key>
	<string>Git Ignore</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>^#.*</string>
			<key>name</key>
			<string>comment.line.number-sign</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(!)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.exclude.git-ignore</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>meta.pattern.exclude.git-ignore</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#wildcards</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#escapes</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#wildcards</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#escapes</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>escapes</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.character.escape</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\[ ]</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\#</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\!</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\!</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>wildcards</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>[*]{3,}</string>
					<key>name</key>
					<string>invalid.asterisk.multiple.git-ignore</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[*][*]</string>
					<key>name</key>
					<string>keyword.operator.asterisk.double.git-ignore</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[*]</string>
					<key>name</key>
					<string>keyword.operator.asterisk.single.git-ignore</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.git-ignore</string>
	<key>uuid</key>
	<string>87d6bed6-feb4-46e2-b4c4-db583abc039e</string>
</dict>
</plist>
